### ISSUE TITLE
error: ‘CodecID’ does not name a type; did you mean ‘AVCodecID’ (While trying to compile v 0.8.0)

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#316]
Had to make a new virtual machine to test Lightspark and when I compile it I got this error:

**--Build files have been written to: /home/lightspark/Downloads/lightspark-lightspark-0.8.0/obj
lightspark@lightspark-VirtualBox:/Downloads/lightspark-lightspark-0.8.0/obj$ make Scanning dependencies of target translations
[  1%] Generating pl.gmo
[  2%] Generating fr.gmo
[  3%] Generating zh_CN.gmo
[  3%] Built target translations
Scanning dependencies of target spark
[  3%] Building CXX object src/CMakeFiles/spark.dir/allclasses.cpp.o
In file included from /home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/scripting/flash/net/flashnet.h:29:0,
                 from /home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/swf.h:32,
                 from /home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/scripting/class.h:28,
                 from /home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/scripting/toplevel/ASString.h:23,
                 from /home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/allclasses.cpp:20:
/home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/backends/decoder.h:324:2: error: ‘CodecID’ does not name a type; did you mean ‘AVCodecID’?
  CodecID LSToFFMpegCodec(LS_AUDIO_CODEC lscodec);
  ^~~~~~~
  AVCodecID
src/CMakeFiles/spark.dir/build.make:62: recipe for target 'src/CMakeFiles/spark.dir/allclasses.cpp.o' failed
make[2]: *** [src/CMakeFiles/spark.dir/allclasses.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/CMakeFiles/spark.dir/all' failed
make[1]: *** [src/CMakeFiles/spark.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2**

Any idea on how to fix it?

**Comment by dbluelle** [comment]
That means that ffmpeg is not properly detected by cmake.
It should be fixed in the current master branch.
You can try to replace your version of  conf/FindLLVM.cmake with the current one.

**Comment by WPFilmmaker** [comment]
@dbluelle You mean the current master branch of ffmpeg?
how do I find the good FindLLVM.cmake to replace it?
Thanks:)

**Comment by dbluelle** [comment]
No, I meant the current master branch of lightspark, right here:
https://github.com/lightspark/lightspark/blob/master/conf/FindLLVM.cmake

**Comment by WPFilmmaker** [comment]
@dbluelle Thank you, I replaced the code for FindLLVM.cmake with the one from the link and saved, but when I re-run I get the same error :/

**Comment by jobermayr** [comment]
Whats says CMake for:
`-- Checking for modules 'libavcodec;libavutil;libavformat'`
`--   Found libavcodec, version ?`
`--   Found libavutil, version ?`
`--   Found libavformat, version ?`
`[...]`
`-- Performing Test HAVE_AVCODECID`
`-- Performing Test HAVE_AVCODECID - ?`

**Comment by WPFilmmaker** [comment]
@jobermayr I don't know f thats what you mant but  I Got:
**lightspark@lightspark-VirtualBox:~/Downloads/lightspark-lightspark-0.8.0/obj$ cmake **-DCMAKE_BUILD_TYPE=Release ..**
-- Found gnash path: /usr/bin/gnash
-- The ASM-NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- LLVM llvm-config found at: /usr/bin/llvm-config
-- LLVM version: 4.0.1
-- LLVM CXX flags: -I/usr/lib/llvm-4.0/include -std=c++0x -fuse-ld=gold -Wl,--no-keep-files-mapped -Wl,--no-map-whole-files -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O2 -DNDEBUG -g1  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM LD flags: -L/usr/lib/llvm-4.0/lib
-- LLVM core libs: -lLLVM-4.0
-- LLVM JIT libs: -lLLVM-4.0
-- LLVM JIT objs:
-- HAVE_SUPPORT_TARGETSELECT_H: 1
-- HAVE_IRBUILDER_H:
-- HAVE_DATALAYOUT_H:
-- HAVE_IR_DATALAYOUT_H:
-- HAVE_IR_VERIFIER_H:
-- HAVE_PASSMANAGER_H:
-- HAVE_TRANSFORMS_SCALAR_GVN_H:
-- Found LLVM: /usr/lib/llvm-4.0/include
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Checking for module 'libavresample'
--   Found libavresample, version 3.5.0
-- Configuring done
CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Target "spark" has an INTERFACE_LINK_LIBRARIES property which differs from
its LINK_INTERFACE_LIBRARIES properties.
INTERFACE_LINK_LIBRARIES
pangocairo-1.0;pango-1.0;gobject-2.0;glib-2.0;cairo;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;-lLLVM-4.0;-lLLVM-4.0;-L/usr/lib/llvm-4.0/lib;lzma;avcodec;avutil;avformat;avresample;curl;rtmp;z;gmp;SDL2;SDL2_mixer;SDL2;/usr/lib/x86_64-linux-gnu/libfreetype.so;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libpcre.so;glibmm-2.4;gobject-2.0;glib-2.0;sigc-2.0;gmodule-2.0;glib-2.0;dl;X11;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libGLEW.so
  LINK_INTERFACE_LIBRARIES
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Generating done
-- Build files have been written to: /home/lightspark/Downloads/lightspark-lightspark-0.8.0/obj**

**Comment by jobermayr** [comment]
Please use a clean build dir (_rm -rf $BUILDDIR/*_). Then you should get all requested information from CMake.

**Comment by WPFilmmaker** [comment]
****I started everything from scratch, changed findLLVM.cmake and did cmake
-DCMAKE_BUILD_TYPE=Release ..**
getting:

**DCMAKE_BUILD_TYPE=Release 
-- Found gnash path: /usr/bin/gnash
-- The ASM-NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- LLVM llvm-config found at: /usr/bin/llvm-config
-- LLVM version: 4.0.1
-- LLVM CXX flags: -I/usr/lib/llvm-4.0/include -std=c++0x -fuse-ld=gold -Wl,--no-keep-files-mapped -Wl,--no-map-whole-files -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O2 -DNDEBUG -g1  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM LD flags: -L/usr/lib/llvm-4.0/lib
-- LLVM core libs: -lLLVM-4.0
-- LLVM JIT libs: -lLLVM-4.0
-- LLVM JIT objs: 
-- HAVE_SUPPORT_TARGETSELECT_H: 1
-- HAVE_IRBUILDER_H: 
-- HAVE_DATALAYOUT_H: 
-- HAVE_IR_DATALAYOUT_H: 
-- HAVE_IR_VERIFIER_H: 
-- HAVE_PASSMANAGER_H: 
-- HAVE_TRANSFORMS_SCALAR_GVN_H:
-- Found LLVM: /usr/lib/llvm-4.0/include
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Checking for module 'libavresample'
--   Found libavresample, version 3.5.0
-- Configuring done
CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "spark" has an INTERFACE_LINK_LIBRARIES property which differs from
  its LINK_INTERFACE_LIBRARIES properties.
  INTERFACE_LINK_LIBRARIES:
  pangocairo-1.0;pango-1.0;gobject-2.0;glib-2.0;cairo;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;-lLLVM-4.0;-lLLVM-4.0;-L/usr/lib/llvm-4.0/lib;lzma;avcodec;avutil;avformat;avresample;curl;rtmp;z;gmp;SDL2;SDL2_mixer;SDL2;/usr/lib/x86_64-linux-gnu/libfreetype.so;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libpcre.so;glibmm-2.4;gobject-2.0;glib-2.0;sigc-2.0;gmodule-2.0;glib-2.0;dl;X11;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libGLEW.so
LINK_INTERFACE_LIBRARIES
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Generating done
-- Build files have been written to: /home/lightspark/Downloads/lightspark-lightspark-0.8.0/obj**

**When I do make I get:**

lightspark@lightspark-VirtualBox:/Downloads/lightspark-lightspark-0.8.0/obj$ make
[  3%] Built target translations
[  4%] Building CXX object src/CMakeFiles/spark.dir/scripting/abc.cpp.o
/home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/scripting/abc.cpp:38:12: fatal error: llvm/Module.h: No such file or directory
include llvm/Module.h
compilation terminated.
src/CMakeFiles/spark.dir/build.make:950: recipe for target 'src/CMakeFiles/spark.dir/scripting/abc.cpp.o' failed
make[2]: *** [src/CMakeFiles/spark.dir/scripting/abc.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/CMakeFiles/spark.dir/all' failed
make[1]: *** [src/CMakeFiles/spark.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
lightspark@lightspark-VirtualBox:~/Downloads/lightspark-lightspark-0.8.0/obj$

**Comment by jobermayr** [comment]
I miss a lot of checks from top level CMakeLists.txt. Did you modify it? Please replace and try it with: https://raw.githubusercontent.com/lightspark/lightspark/master/CMakeLists.txt

**Comment by WPFilmmaker** [comment]
@jobermayr No I didn't modify CMakeLists.txt, I replaced it with what you posted and I get:

lightspark@lightspark-VirtualBox:~/Downloads/lightspark-lightspark-0.8.0/obj$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Found gnash path: /usr/bin/gnash
-- The ASM-NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- LLVM llvm-config found at: /usr/bin/llvm-config
-- LLVM version: 4.0.1
-- LLVM CXX flags: -I/usr/lib/llvm-4.0/include -std=c++0x -fuse-ld=gold -Wl,--no-keep-files-mapped -Wl,--no-map-whole-files -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O2 -DNDEBUG -g1  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM LD flags: -L/usr/lib/llvm-4.0/lib
-- LLVM core libs: -lLLVM-4.0
-- LLVM JIT libs: -lLLVM-4.0
-- LLVM JIT objs:
-- HAVE_SUPPORT_TARGETSELECT_H: 1
-- HAVE_IRBUILDER_H:
-- HAVE_DATALAYOUT_H:
-- HAVE_IR_DATALAYOUT_H:
-- HAVE_IR_VERIFIER_H:
-- HAVE_PASSMANAGER_H:
-- HAVE_TRANSFORMS_SCALAR_GVN_H:
-- Found LLVM: /usr/lib/llvm-4.0/include
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Checking for module 'libavresample'
--   Found libavresample, version 3.5.0
-- Configuring done
CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
 
 Target "spark" has an INTERFACE_LINK_LIBRARIES property which differs from
 its LINK_INTERFACE_LIBRARIES properties.
 
 INTERFACE_LINK_LIBRARIES:
 pangocairo-1.0;pango-1.0;gobject-2.0;glib-2.0;cairo;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;-lLLVM-4.0;-lLLVM-4.0;-L/usr/lib/llvm-4.0/lib;lzma;avcodec;avutil;avformat;avresample;curl;rtmp;z;gmp;SDL2;SDL2_mixer;SDL2;/usr/lib/x86_64-linux-gnu/libfreetype.so;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libpcre.so;glibmm-2.4;gobject-2.0;glib-2.0;sigc-2.0;gmodule-2.0;glib-2.0;dl;X11;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libGLEW.so

  LINK_INTERFACE_LIBRARIES:
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Generating done
-- Build files have been written to: /home/lightspark/Downloads/lightspark-lightspark-0.8.0/obj

**Comment by WPFilmmaker** [comment]
And this is the output for _make_:

lightspark@lightspark-VirtualBox:/Downloads/lightspark-lightspark-0.8.0/obj$ make
[  3%] Built target translations
[  4%] Building CXX object src/CMakeFiles/spark.dir/scripting/abc.cpp.o
/home/lightspark/Downloads/lightspark-lightspark-0.8.0/src/scripting/abc.cpp:38:12: fatal error: llvm/Module.h: No such file or directory
include <llvm/Module.h>
compilation terminated.
src/CMakeFiles/spark.dir/build.make:950: recipe for target 'src/CMakeFiles/spark.dir/scripting/abc.cpp.o' failed
make[2]: *** [src/CMakeFiles/spark.dir/scripting/abc.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/CMakeFiles/spark.dir/all' failed
make[1]: *** [src/CMakeFiles/spark.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
lightspark@lightspark-VirtualBox:~/Downloads/lightspark-lightspark-0.8.0/obj$

**Comment by WPFilmmaker** [comment]
Just for the sake of information, The virtualbox I was using to test lightspark got mesed up by an annoying bug in Xubuntu 17.10 which sends the login in loop=had to make another one from scratch, sticking to 16.04 til the next LTS gets released.

**Comment by dbluelle** [comment]
works in 0.8.1

**Comment by Zolo101** [comment]
(still got this error on 0.8.1) and also just a quick PSA: if your on WSL, do not just do " rm -rf $BUILDDIR/*" as it breaks the WSL distro and everything will be lost and you'll have to reinstalll everything again.

**Comment by Mis012** [comment]
I get this issue on the latest master still

**Comment by Mis012** [comment]
nvm, seems that nuking the builddir fixes it

**Comment by huwdp** [comment]
I had a similar issue but after a hard git reset I followed the guide again in README file and it worked. I didn't run ```cmake -DCMAKE_BUILD_TYPE=Release ..``` within the obj folder originally
