### ISSUE TITLE
Lightspark fails to build with LLVM 3.9.0

### ISSUE THREAD

**Issue by euspectre** [lightspark/lightspark#271]
Lightspark git rev. 968d61f1 (2016-09-04).
OS: ROSA Linux R8, x86_64
LLVM 3.9.0.

When I try to build lightspark, the following error is reported:

<pre>
/builddir/build/BUILD/lightspark-0.7.2/src/scripting/abc.cpp: 
In static member function 'static void lightspark::ABCVm::Run(lightspark::ABCVm*)':
/builddir/build/BUILD/lightspark-0.7.2/src/scripting/abc.cpp:1656:16: 
error: 'createGVNPass' is not a member of 'llvm'
   th->FPM->add(llvm::createGVNPass());
</pre>

Here is how the build system tries to compile that file:
<pre>
[ 32%] Building CXX object src/CMakeFiles/spark.dir/scripting/abc.cpp.o

cd /builddir/build/BUILD/lightspark-0.7.2/build/src && 
/usr/bin/c++  
 -DAUDIO_BACKEND=\"pulseaudio\" -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION 
-DENABLE_CURL -DENABLE_LIBAVCODEC -DENABLE_RTMP 
-DGNASH_PATH=\"/usr/bin/gnash\" -DHAVE_ATOMIC -DHAVE_AVCODECID 
-DHAVE_AVCODEC_ALLOC_CONTEXT3 -DHAVE_AVCODEC_DECODE_AUDIO3 
-DHAVE_AVCODEC_DECODE_AUDIO4 -DHAVE_AVCODEC_DECODE_VIDEO2 
-DHAVE_AVCODEC_OPEN2 -DHAVE_AVFORMAT_CLOSE_INPUT 
-DHAVE_AVFORMAT_FIND_STREAM_INFO -DHAVE_AVIO_ALLOC_CONTEXT 
-DHAVE_AV_FRAME_ALLOC -DHAVE_AV_FRAME_UNREF -DHAVE_AV_PACKET_UNREF
 -DHAVE_IR_DATALAYOUT_H -DHAVE_IR_VERIFIER_H -DHAVE_NEW_GLIBMM_THREAD_API 
-DHAVE_SUPPORT_TARGETSELECT_H 
-DLLVM_31 -DLLVM_34 -DLLVM_35 -DLLVM_36 -DLLVM_37 -DLLVM_38 
-DLS_DATADIR=\"/usr/share/lightspark\" -DPRIVATELIBDIR=\"/usr/lib64/lightspark\"
 -Dspark_EXPORTS 
-I/builddir/build/BUILD/lightspark-0.7.2/build -I/usr/include/glibmm-2.4 
-I/usr/lib64/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 
-I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/usr/include/freetype2 
-I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 
-I/usr/include/harfbuzz -I/usr/include/libxml2 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include 
-I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/builddir/build/BUILD/lightspark-0.7.2/src -I/builddir/build/BUILD/lightspark-0.7.2/src/scripting  
-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches 
-Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2
-ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 
-fPIC -std=gnu++11  -Wall -Wnon-virtual-dtor -Woverloaded-virtual -pipe -fvisibility=hidden
 -fvisibility-inlines-hidden -std=c++11 -Wdisabled-optimization -Wextra -Wno-unused-parameter 
-Wno-invalid-offsetof -g -O2 -DNDEBUG -fPIC   -o CMakeFiles/spark.dir/scripting/abc.cpp.o 
-c /builddir/build/BUILD/lightspark-0.7.2/src/scripting/abc.cpp
</pre>

**Comment by euspectre** [comment]
Yes, Lightspark builds OK with LLVM 3.9 now. Thanks a lot!
