### ISSUE TITLE
lightspark fails to build with boost 1.72.0

### ISSUE THREAD

**Issue by david-geiger** [lightspark/lightspark#442]
HI,

I tried on Mageia Cauldron to build latest lightspark against boost 1.72.0 but it fails to build with:

> In file included from /usr/include/boost/bimap/detail/map_view_base.hpp:40,
                 from /usr/include/boost/bimap/views/map_view.hpp:22,
                 from /usr/include/boost/bimap/set_of.hpp:39,
                 from /usr/include/boost/bimap/detail/manage_bimap_key.hpp:26,
                 from /usr/include/boost/bimap/detail/bimap_core.hpp:43,
                 from /usr/include/boost/bimap/bimap.hpp:61,
                 from /usr/include/boost/bimap.hpp:13,
                 from /home/iurt/rpmbuild/BUILD/lightspark-0.8.2/src/scripting/flash/display/flashdisplay.h:23,
                 from /home/iurt/rpmbuild/BUILD/lightspark-0.8.2/src/backends/rendering_context.cpp:36:
/usr/include/boost/bimap/detail/map_view_iterator.hpp:139:5: error: expected ';' at end of member declaration
  139 |     BOOST_BIMAP_MAP_VIEW_ITERATOR_SERIALIZATION_SUPPORT
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/bimap/detail/map_view_iterator.hpp:175:5: error: expected ';' at end of member declaration
  175 |     BOOST_BIMAP_MAP_VIEW_ITERATOR_SERIALIZATION_SUPPORT
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/bimap/detail/map_view_iterator.hpp:216:5: error: expected ';' at end of member declaration
  216 |     BOOST_BIMAP_MAP_VIEW_ITERATOR_SERIALIZATION_SUPPORT
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/bimap/detail/map_view_iterator.hpp:253:5: error: expected ';' at end of member declaration
  253 |     BOOST_BIMAP_MAP_VIEW_ITERATOR_SERIALIZATION_SUPPORT
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/bimap/detail/map_view_iterator.hpp:294:5: error: expected ';' at end of member declaration
  294 |     BOOST_BIMAP_MAP_VIEW_ITERATOR_SERIALIZATION_SUPPORT
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/bimap/detail/map_view_iterator.hpp:330:5: error: expected ';' at end of member declaration
  330 |     BOOST_BIMAP_MAP_VIEW_ITERATOR_SERIALIZATION_SUPPORT

Full build log:
[build.0.20200126215853.log](https://github.com/lightspark/lightspark/files/4118065/build.0.20200126215853.log)

**Comment by david-geiger** [comment]
Ouuppsss sorry already done here https://github.com/lightspark/lightspark/issues/406
