### ISSUE TITLE
Doodle God 2 - Error #1006: model:Model::encode is not a function.

### ISSUE THREAD

**Issue by huwdp** [lightspark/lightspark#726]
**Steps to re-produce:**
1. Run file under Lightspark.
2. Press play button.
2. Error "Error #1006: model:Model::encode is not a function." will appear.

Lightspark version: c0aaa1a1bc26237f57553a3e93d5164c79b2e149

File: https://github.com/lightspark/lightspark/files/5016521/doodle-god-2-11411.zip

I'll git bisect and post the results here tomorrow.
