### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by orbea** [lightspark/lightspark#319]
OS: `Slackware64-current`
`gcc-7.3.0`

When trying to build the current lightspark git master (a0c196b00c879947ba04670b9c93749982bd94cf) I encountered this build error.
```
[ 90%] Building CXX object src/CMakeFiles/spark.dir/3rdparty/pugixml/src/pugixml.cpp.o
[ 90%] Building CXX object src/CMakeFiles/spark.dir/platforms/fastpaths_x86.cpp.o
[ 91%] Building ASM-NASM object src/CMakeFiles/spark.dir/platforms/fastpaths_amd64.asm.o
/tmp/SBo/lightspark/src/scripting/toplevel/toplevel.cpp:291:6: error: prototype for ‘void lightspark::SyntheticFunction::call(lightspark::asAtom&, lightspark::asAtom&, lightspark::asAtom*, uint32_t)’ does not match any in class ‘lightspark::SyntheticFunction’
 void SyntheticFunction::call(asAtom& ret, asAtom& obj, asAtom *args, uint32_t numArgs)
      ^~~~~~~~~~~~~~~~~
In file included from /tmp/SBo/lightspark/src/scripting/abc.h:35:0,
                 from /tmp/SBo/lightspark/src/scripting/toplevel/toplevel.cpp:37:
/tmp/SBo/lightspark/src/scripting/toplevel/toplevel.h:500:7: error: candidate is: void lightspark::SyntheticFunction::call(lightspark::asAtom&, lightspark::asAtom&, lightspark::asAtom*, uint32_t, bool)
  void call(asAtom &ret, asAtom& obj, asAtom *args, uint32_t num_args, bool coerceresult);
       ^~~~
make[2]: *** [src/CMakeFiles/spark.dir/build.make:2847: src/CMakeFiles/spark.dir/scripting/toplevel/toplevel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: src/CMakeFiles/spark.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```
Full build log - https://pastebin.com/Ln9cUf7r

I then used git bisect to find the first bad commit.
```
50c8d45a5e295673adb56212cef7338198bb080c is the first bad commit
commit 50c8d45a5e295673adb56212cef7338198bb080c
Author: Ludger Krämer <dbluelle@onlinehome.de>
Date:   Sat Mar 31 12:18:54 2018 +0200

    don't coerce the return value of sort comparison functions
    This has to be done because otherwise coercing to int may loose the sign
    of the result (avmplus does the same).
    fixes #318

:040000 040000 e5d2a7e62d8b38d940caacb298e69f768a4ea9fa 6aa414570561ab5868ac30b9df12fd5570fadc3c M	src
```
50c8d45a5e295673adb56212cef7338198bb080c

**Comment by orbea** [comment]
Thanks, it builds now!
